name: hobbit
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  english_words: ^4.0.0
  provider: ^6.0.0
  table_calendar: ^3.0.9
  image_picker: ^1.0.6
  camera: ^0.10.5+9
  path_provider: ^2.1.1
  path: ^1.8.3
  speech_to_text: ^6.5.1
  http: ^1.1.2
  google_maps_flutter: ^2.5.2
  location: ^5.0.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  intl: ^0.18.1
  mysql1: ^0.20.0
  shared_preferences: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true